services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    Linderp\SuluBaseBundle\Common\DoctrineListRepresentationFactory:
    Linderp\SuluBaseBundle\Content\Types\ThemeColorPropertyResolver:
        tags: [ 'sulu_content.property_resolver' ]
    Linderp\SuluBaseBundle\Twig\ThemeColorExtension:
    Linderp\SuluBaseBundle\Admin\Metadata\GeneratedLinkPropertyMetadataMapper:
        arguments:
            $textPropertyMetadataMapper: '@sulu_admin.property_metadata_mapper.text'
        tags:
            - { name: 'sulu_admin.property_metadata_mapper', type: 'generated_link' }
